---
- hosts: BlueServer
  become: true
  tasks:

  - name: install web based packages and ftp server to BlueTeam server
    tags: Blue,level1
    apt:
      name: 
        - apache2
        - libapache2-mod-php
        - mariadb-server
        - vsftpd
      state: latest
    
  - name: copy default html file to BlueServer
    tags: Blue,apache,html,configs
    copy:
      src: configs/default_blue_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644

- hosts: ShortStoryDesktops
  tags: SS,Desktop
  tasks:

  - name: install kde-desktop chromium and konsole to Short Stories desktop
    apt:
      name:
      - task-kde-desktop
      - chromium
      - konsole
      state: latest
  - name: enable desktop on startup
    service:
      name: sddm
      state: started
      enabled: yes

- hosts: ShortStorySecureServer
  tags: SS,SecureServer
  become: true
  tasks:

  - name: install apache2, SSL, and other components to secure server
    apt:
      name:
      - apache2
      - openssl
      state: latest
        
- hosts: LeakedPasswords
  tags: SS,Red,http
  become: true
  tasks:

  - name: install apache2, php, and aptitude to leaked password red bot
    apt:
      name: 
        - apache2
        - libapache2-mod-php
        - aptitude
      state: latest

  - name: copy website files to LeakedPasswords red bot
    copy:
      src: configs/bad_login.php
      dest: /var/www/html/bad_login.php
      owner: root
      group: root
      mode: 0777      
  - name: copy over other website files to LeakdPasswords red bot
    copy:
      src: configs/bad_home.html
      dest: /var/www/html/bad_home.html
      owner: root
      group: root
      mode: 0777
      

#  - name: install mysql database
#    shell: export DEBIAN_FRONTEND=noninteractive; wget https://dev.mysql.com/get/mysql-apt-config_0.8.13-1_all.deb; dpkg -i mysql-appt-config-_0.8.13-1_all.deb ; sudo apt update; aptitude install mysql-server -y;

      


- hosts: 
    RedAttacker
    RedBots
  tags: Red,Kali,level1
  become: true
  tasks:

  - name: add Kali repos to Red Team machines
    shell: sh -c "echo 'deb https://http.kali.org/kali kali-rolling main non-free contrib' > /etc/apt/sources.list.d/kali.list"
    
  - name: install gnupg to Red Team machines
    apt:
      name: gnupg

  - name: verify kali repo public keys of Red team machines
    shell: wget 'https://archive.kali.org/archive-key.asc'; apt-key add archive-key.asc 

  - name: update with new packages for Red team Machines
    shell: apt update

  - name: set repo priority below standard debian packages for Red team Machines
    shell: "echo 'Package: *' > /etc/apt/preferences.d/kali.pref; echo 'Pin: release a=kali-rolling' >> /etc/apt/preferences.d/kali.pref; echo 'Pin-Priority: 50' >> /etc/apt/preferences.d/kali.pref"

  - name: update packages with new priority for Red Team Machines
    shell: apt update

  - name: install aptitude for kali packages
    apt:
      name: aptitude
      state: latest

  - name: set installation of kali packages to be non interactive and use default options
    shell: export DEBIAN_FRONTEND=noninteractive

- hosts:
    RedAttacker
    RedBots
  tags: Red,Kali,level2, metasploit
  become: true
  tasks:

  - name: install metasploit onto RedTeam machines
    shell: aptitude install -t kali-rolling metasploit-framework -y

- hosts:
    RedAttacker
  tags: ansible,dos,botnet,configs
  become: true
  tasks:

  - name: install ansible to RedAttacker
    shell: aptitude install -t kali-rolling ansible

  - name: add botnetinventory file to RedAttacker
    copy:
      src: configs/red_inventory
      dest: /home/student/
      owner: student
      group: student
      mode: 0777
    
