---

- hosts: all
  become: true
  tasks:

  - name: update repository index 
    apt: 
      update_cache: yes
#only installs apache if the distro is Ubuntu or debian
    when: ansible_distribution in ["Ubuntu", "Debian"]

  - name: update repository index
    dnf:
      update_cache: yes
#only installs apache if the distro is CentOS
    when: ansible_distribution in ["CentOS" ]


  - name: install apache2 package Debian
    apt:
      name: apache2
      state: latest
    when: ansible_distribution == "Debian"


  - name: add php support for apache Debian
    apt:
      name: libapache2-mod-php
      state: latest
    when: ansible_distribution == "Debian"


  - name: install apache2 package Centos
    dnf:
      name: httpd
      state: latest
    when: ansible_distribution == "CentOS"


  - name: add php support for apache CentOS
    dnf:
      name: php
      state: latest
    when: ansible_distribution == "CentOS"


