---

- hosts: all
  become: true
  tasks:



  - name: install apache2 and php packages 
    package:
      name: 
#installs the version of apache and php that is associated with debian and centos
        - "{{ apache_package }}"
        - "{{ php_package }}"
      state: latest
      update_cache: yes



